#!/bin/bash
# This script holds various convinence aliases and bash functions.
# If a given bash function (or set of functions) grows substantially,
# It should be forked into its own script file.

# SSH
alias cofree-coffee="ssh solomon@cofree.coffee"
alias ours="ssh solomon@142.93.159.251"

# Applications
alias emacs='emacs -nw'
alias mutt=neomutt
alias ls="exa -l"
alias ns="nix-shell"
alias refresh='exec $SHELL -l'
