#!/bin/bash
# Google Cloud SDK Init script

# Update PATH for the Google Cloud SDK.
if [ -f "${HOME}/.google-cloud-sdk/path.bash.inc" ]; then
  . "${HOME}/.google-cloud-sdk/path.bash.inc";
fi

# Shell command completion for gcloud.
if [ -f "${HOME}/.google-cloud-sdk/completion.bash.inc" ]; then
  . "${HOME}/.google-cloud-sdk/completion.bash.inc";
fi
